// ═══════════════════════════════════════════════════════════════════
// APP GENERATOR — Generates complete applications with full filesystems
//
// When the AI builds an app, instead of generating a single HTML file,
// this module generates a complete app directory structure:
//
//   /system/apps/<id>/
//     manifest.json    — app metadata
//     index.html       — entry point HTML
//     styles.css       — app styles
//     app.js           — app logic
//     README.md        — documentation
//     data/            — app data directory
//
// The app is then registered with the OS so it appears in the app
// launcher and can be opened like any built-in app.
// ═══════════════════════════════════════════════════════════════════

import { vfs, SYSTEM_VFS_APP_ID } from './fileSystem';
import { memory } from './memory';
import { eventBus } from './eventBus';
import { kernelLog } from './log';
import { aiService } from '../services/puterService';
import { useOS } from '../store/osStore';

const APPS_DIR = '/system/apps';

export interface GeneratedApp {
  appId: string;
  name: string;
  description: string;
  path: string;
  entryFile: string;
  files: string[];
  manifest: AppManifest;
}

export interface AppManifest {
  id: string;
  name: string;
  description: string;
  version: string;
  author: string;
  icon: string;
  entry: string;
  category: string;
  permissions: string[];
  generatedAt: number;
  generatedBy: string;
}

function parseAppJson(response: string): any {
  if (!response || typeof response !== 'string') {
    throw new Error('Empty AI response');
  }

  // 1. If wrapped in markdown code fence, extract fence content
  const fenceMatch = response.match(/```(?:json)?\s*([\s\S]*?)```/i);
  let candidate = fenceMatch ? fenceMatch[1].trim() : response.trim();

  // 2. Direct JSON parse
  try {
    return JSON.parse(candidate);
  } catch {}

  // 3. Extract outermost curly braces
  const firstBrace = candidate.indexOf('{');
  const lastBrace = candidate.lastIndexOf('}');
  if (firstBrace !== -1 && lastBrace > firstBrace) {
    const braceContent = candidate.slice(firstBrace, lastBrace + 1);
    try {
      return JSON.parse(braceContent);
    } catch {}

    // 4. Try removing trailing commas
    try {
      const sanitized = braceContent.replace(/,\s*([}\]])/g, '$1');
      return JSON.parse(sanitized);
    } catch {}
  }

  // 5. Fallback: If AI returned an HTML document directly instead of JSON, decompose it
  if (candidate.includes('<!DOCTYPE html>') || candidate.includes('<html')) {
    const html = candidate;
    // Extract title
    const titleMatch = html.match(/<title>([^<]+)<\/title>/i);
    const name = titleMatch ? titleMatch[1].trim() : 'Synthesized App';

    // Extract style
    const styleMatch = html.match(/<style[^>]*>([\s\S]*?)<\/style>/i);
    const stylesCss = styleMatch ? styleMatch[1].trim() : '';

    // Extract script
    const scriptMatch = html.match(/<script(?![^>]*src)[^>]*>([\s\S]*?)<\/script>/i);
    const appJs = scriptMatch ? scriptMatch[1].trim() : '';

    return {
      name,
      description: 'AI Generated Application',
      icon: '⚡',
      category: 'utility',
      version: '1.0.0',
      indexHtml: html,
      stylesCss,
      appJs: appJs || '// Application initialized\nconsole.log("App loaded");',
      readme: `# ${name}\n\nGenerated by NexusOS AI.`
    };
  }

  throw new Error('AI response did not contain a valid JSON application structure');
}

class AppGenerator {
  async generate(description: string, suggestedName?: string): Promise<GeneratedApp> {
    const appId = `gen_${Date.now().toString(36)}`;
    const appDir = `${APPS_DIR}/${appId}`;

    if (!vfs.stat(APPS_DIR)) {
      vfs.createDirRecursive(APPS_DIR, SYSTEM_VFS_APP_ID);
    }
    if (!vfs.stat(appDir)) {
      vfs.createDir(appDir, SYSTEM_VFS_APP_ID);
    }

    const prompt = `You are the Application Architect of NexusOS, an advanced AI-native operating system.

Synthesize a COMPLETE, HIGH-QUALITY, FULLY FUNCTIONAL web application for:
"${description}"

Return ONLY a valid JSON object with this exact structure:
{
  "name": "App Name",
  "description": "Clear one-sentence description",
  "icon": "Emoji symbol (e.g. ⚡, 🎨, 🎵, 📊)",
  "category": "utility|productivity|creative|game|education",
  "version": "1.0.0",
  "indexHtml": "<!DOCTYPE html>\\n<html lang=\\"en\\">\\n<head>\\n  <meta charset=\\"UTF-8\\">\\n  <title>App</title>\\n  <link rel=\\"stylesheet\\" href=\\"styles.css\\">\\n</head>\\n<body>\\n  <!-- Fully designed HTML structure -->\\n  <script src=\\"app.js\\"></script>\\n</body>\\n</html>",
  "stylesCss": "/* Modern polished dark design (bg #0a0a0f, accent #10b981) */",
  "appJs": "// Complete interactive vanilla JS with full state & event handlers",
  "readme": "# Documentation and features"
}

REQUIREMENTS:
1. PURE JSON ONLY. No markdown wrapper, no conversational text before or after.
2. The app must be 100% COMPLETE and FULLY FUNCTIONAL. No TODOs, no placeholders.
3. Dark theme aesthetic: bg #0a0a0f, card #12121a, border #27273a, text #e2e8f0, accent #10b981.
4. All user actions (buttons, forms, sliders, tabs) must work with real vanilla JavaScript logic.`;

    let appData: any;
    try {
      const rules = useOS.getState().kernelRules;
      const response = await aiService.generateOnce(prompt, rules, 'architect');
      appData = parseAppJson(response);
    } catch (e: any) {
      kernelLog.error('[AppGenerator] AI generation failed:', e?.message);
      throw new Error(`App generation failed: ${e?.message}`);
    }

    if (!appData.indexHtml) {
      throw new Error('AI response missing required indexHtml');
    }

    const name = suggestedName || appData.name || 'Generated App';
    const files: string[] = [];

    const indexPath = `${appDir}/index.html`;
    vfs.writeFile(indexPath, appData.indexHtml, SYSTEM_VFS_APP_ID);
    files.push(indexPath);

    const cssPath = `${appDir}/styles.css`;
    vfs.writeFile(cssPath, appData.stylesCss || '', SYSTEM_VFS_APP_ID);
    files.push(cssPath);

    const jsPath = `${appDir}/app.js`;
    vfs.writeFile(jsPath, appData.appJs || '', SYSTEM_VFS_APP_ID);
    files.push(jsPath);

    const readmePath = `${appDir}/README.md`;
    const readmeContent = appData.readme || `# ${name}\n\n${appData.description || ''}\n\nGenerated by NexusOS AI.`;
    vfs.writeFile(readmePath, readmeContent, SYSTEM_VFS_APP_ID);
    files.push(readmePath);

    const manifest: AppManifest = {
      id: appId,
      name,
      description: appData.description || description,
      version: appData.version || '1.0.0',
      author: 'NexusOS AI',
      icon: appData.icon || '📦',
      entry: 'index.html',
      category: appData.category || 'utility',
      permissions: ['vfs.read', 'vfs.write', 'network'],
      generatedAt: Date.now(),
      generatedBy: 'ai',
    };
    const manifestPath = `${appDir}/manifest.json`;
    vfs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), SYSTEM_VFS_APP_ID);
    files.push(manifestPath);

    const dataDir = `${appDir}/data`;
    vfs.createDir(dataDir, SYSTEM_VFS_APP_ID);
    vfs.writeFile(`${dataDir}/.keep`, '', SYSTEM_VFS_APP_ID);

    const os = useOS.getState();
    if (typeof (os as any).registerCustomApp === 'function') {
      (os as any).registerCustomApp({
        id: appId,
        name,
        icon: undefined,
        defaultSize: { width: 960, height: 720 },
        isCustom: true,
        sourcePath: indexPath,
        manifest,
        permissions: manifest.permissions,
      });
    }

    memory.remember(`Generated app: "${name}" — ${description} (path: ${appDir})`, ['app', 'generated', 'ai']);

    os.addNotification({
      title: '✅ App Generated',
      message: `"${name}" created with ${files.length} files at ${appDir}`,
      type: 'success',
    } as any);

    eventBus.emit('app:generated', { appId, name, path: appDir });
    kernelLog.info(`[AppGenerator] Generated "${name}" with ${files.length} files`);

    return {
      appId,
      name,
      description: manifest.description,
      path: appDir,
      entryFile: indexPath,
      files,
      manifest,
    };
  }

  list(): AppManifest[] {
    const apps: AppManifest[] = [];
    if (!vfs.stat(APPS_DIR)) return apps;
    const dirs = vfs.listDir(APPS_DIR, SYSTEM_VFS_APP_ID) || [];
    for (const dir of dirs) {
      const manifestPath = `${APPS_DIR}/${dir}/manifest.json`;
      const raw = vfs.readFile(manifestPath, SYSTEM_VFS_APP_ID);
      if (!raw) continue;
      try {
        apps.push(JSON.parse(raw));
      } catch {}
    }
    return apps;
  }

  delete(appId: string): boolean {
    const appDir = `${APPS_DIR}/${appId}`;
    if (!vfs.stat(appDir)) return false;
    this.deleteRecursive(appDir);
    eventBus.emit('app:deleted', { appId });
    return true;
  }

  private deleteRecursive(path: string) {
    const stat = vfs.stat(path);
    if (stat?.type === 'directory') {
      const items = vfs.listDir(path, SYSTEM_VFS_APP_ID) || [];
      for (const item of items) {
        this.deleteRecursive(`${path}/${item}`);
      }
    }
    vfs.delete(path, SYSTEM_VFS_APP_ID);
  }

  /**
   * Get the entry HTML for a generated app, with CSS and JS inlined
   * so it works in an iframe without path resolution issues.
   */
  getInlinedEntry(appId: string): string | null {
    const appDir = `${APPS_DIR}/${appId}`;
    let html = vfs.readFile(`${appDir}/index.html`, SYSTEM_VFS_APP_ID);
    if (!html) return null;
    const css = vfs.readFile(`${appDir}/styles.css`, SYSTEM_VFS_APP_ID) || '';
    const js = vfs.readFile(`${appDir}/app.js`, SYSTEM_VFS_APP_ID) || '';

    // Inline CSS
    html = html.replace(
      /<link[^>]*href=["']styles\.css["'][^>]*>/gi,
      `<style>\n${css}\n</style>`
    );
    // Inline JS
    html = html.replace(
      /<script[^>]*src=["']app\.js["'][^>]*><\/script>/gi,
      `<script>\n${js}\n</script>`
    );
    // If no link/script tags found, append
    if (css && !html.includes('<style>')) {
      html = html.replace('</head>', `<style>\n${css}\n</style>\n</head>`);
    }
    if (js && !html.includes('<script>')) {
      html = html.replace('</body>', `<script>\n${js}\n</script>\n</body>`);
    }
    return html;
  }
}

export const appGenerator = new AppGenerator();
