// ═══════════════════════════════════════════════════════════════════
// APP GENERATOR — Generates complete applications with full filesystems
//
// When the AI builds an app, instead of generating a single HTML file,
// this module generates a complete app directory structure:
//
//   /system/apps/<id>/
//     manifest.json    — app metadata
//     index.html       — entry point HTML
//     styles.css       — app styles
//     app.js           — app logic
//     README.md        — documentation
//     data/            — app data directory
//
// The app is then registered with the OS so it appears in the app
// launcher and can be opened like any built-in app.
// ═══════════════════════════════════════════════════════════════════

import { vfs, SYSTEM_VFS_APP_ID } from './fileSystem';
import { memory } from './memory';
import { eventBus } from './eventBus';
import { kernelLog } from './log';
import { aiService } from '../services/puterService';
import { useOS } from '../store/osStore';

const APPS_DIR = '/system/apps';

export interface GeneratedApp {
  appId: string;
  name: string;
  description: string;
  path: string;
  entryFile: string;
  files: string[];
  manifest: AppManifest;
}

export interface AppManifest {
  id: string;
  name: string;
  description: string;
  version: string;
  author: string;
  icon: string;
  entry: string;
  category: string;
  permissions: string[];
  generatedAt: number;
  generatedBy: string;
}

class AppGenerator {
  async generate(description: string, suggestedName?: string): Promise<GeneratedApp> {
    const appId = `gen_${Date.now().toString(36)}`;
    const appDir = `${APPS_DIR}/${appId}`;

    if (!vfs.stat(APPS_DIR)) {
      vfs.createDirRecursive(APPS_DIR, SYSTEM_VFS_APP_ID);
    }
    if (!vfs.stat(appDir)) {
      vfs.createDir(appDir, SYSTEM_VFS_APP_ID);
    }

    const prompt = `You are an app generator for NexusOS, an AI-native operating system.

Generate a COMPLETE, FUNCTIONAL web application for: "${description}"

The app must be a single-page application that works standalone in an iframe.
Return ONLY a JSON object with this exact structure (no markdown, no explanation):

{
  "name": "App Name (2-3 words)",
  "description": "One sentence description",
  "icon": "emoji that represents the app",
  "category": "utility|productivity|creative|game|education",
  "version": "1.0.0",
  "indexHtml": "complete HTML document with <!DOCTYPE html>, including <head> and <body>. Link to styles.css and app.js. Must be fully functional.",
  "stylesCss": "complete CSS for the app. Modern, clean design with good UX. Dark theme preferred (bg #0a0a0f, accent #10b981).",
  "appJs": "complete JavaScript. Must make the app fully functional. No external dependencies — vanilla JS only.",
  "readme": "Markdown documentation: what the app does, how to use it, features."
}

CRITICAL REQUIREMENTS:
1. The app must be FULLY FUNCTIONAL — not a mockup or placeholder
2. All HTML/CSS/JS must be production-quality
3. No external CDN dependencies — everything self-contained
4. The JavaScript must actually work when the page loads
5. Include proper error handling and edge cases
6. Make it look polished and professional

Return ONLY the JSON, nothing else.`;

    let appData: any;
    try {
      const rules = useOS.getState().kernelRules;
      const response = await aiService.generateOnce(prompt, rules, 'architect');
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        throw new Error('AI did not return valid JSON');
      }
      appData = JSON.parse(jsonMatch[0]);
    } catch (e: any) {
      kernelLog.error('[AppGenerator] AI generation failed:', e?.message);
      throw new Error(`App generation failed: ${e?.message}`);
    }

    if (!appData.indexHtml || !appData.appJs) {
      throw new Error('AI response missing required fields (indexHtml or appJs)');
    }

    const name = suggestedName || appData.name || 'Generated App';
    const files: string[] = [];

    const indexPath = `${appDir}/index.html`;
    vfs.writeFile(indexPath, appData.indexHtml, SYSTEM_VFS_APP_ID);
    files.push(indexPath);

    const cssPath = `${appDir}/styles.css`;
    vfs.writeFile(cssPath, appData.stylesCss || '', SYSTEM_VFS_APP_ID);
    files.push(cssPath);

    const jsPath = `${appDir}/app.js`;
    vfs.writeFile(jsPath, appData.appJs, SYSTEM_VFS_APP_ID);
    files.push(jsPath);

    const readmePath = `${appDir}/README.md`;
    const readmeContent = appData.readme || `# ${name}\n\n${appData.description || ''}\n\nGenerated by NexusOS AI.`;
    vfs.writeFile(readmePath, readmeContent, SYSTEM_VFS_APP_ID);
    files.push(readmePath);

    const manifest: AppManifest = {
      id: appId,
      name,
      description: appData.description || description,
      version: appData.version || '1.0.0',
      author: 'NexusOS AI',
      icon: appData.icon || '📦',
      entry: 'index.html',
      category: appData.category || 'utility',
      permissions: ['vfs.read', 'vfs.write', 'network'],
      generatedAt: Date.now(),
      generatedBy: 'ai',
    };
    const manifestPath = `${appDir}/manifest.json`;
    vfs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), SYSTEM_VFS_APP_ID);
    files.push(manifestPath);

    const dataDir = `${appDir}/data`;
    vfs.createDir(dataDir, SYSTEM_VFS_APP_ID);
    vfs.writeFile(`${dataDir}/.keep`, '', SYSTEM_VFS_APP_ID);

    const os = useOS.getState();
    if (typeof (os as any).registerCustomApp === 'function') {
      (os as any).registerCustomApp({
        id: appId,
        name,
        icon: undefined,
        defaultSize: { width: 960, height: 720 },
        isCustom: true,
        sourcePath: indexPath,
        manifest,
        permissions: manifest.permissions,
      });
    }

    memory.remember(`Generated app: "${name}" — ${description} (path: ${appDir})`, ['app', 'generated', 'ai']);

    os.addNotification({
      title: '✅ App Generated',
      message: `"${name}" created with ${files.length} files at ${appDir}`,
      type: 'success',
    } as any);

    eventBus.emit('app:generated', { appId, name, path: appDir });
    kernelLog.info(`[AppGenerator] Generated "${name}" with ${files.length} files`);

    return {
      appId,
      name,
      description: manifest.description,
      path: appDir,
      entryFile: indexPath,
      files,
      manifest,
    };
  }

  list(): AppManifest[] {
    const apps: AppManifest[] = [];
    if (!vfs.stat(APPS_DIR)) return apps;
    const dirs = vfs.listDir(APPS_DIR, SYSTEM_VFS_APP_ID) || [];
    for (const dir of dirs) {
      const manifestPath = `${APPS_DIR}/${dir}/manifest.json`;
      const raw = vfs.readFile(manifestPath, SYSTEM_VFS_APP_ID);
      if (!raw) continue;
      try {
        apps.push(JSON.parse(raw));
      } catch {}
    }
    return apps;
  }

  delete(appId: string): boolean {
    const appDir = `${APPS_DIR}/${appId}`;
    if (!vfs.stat(appDir)) return false;
    this.deleteRecursive(appDir);
    eventBus.emit('app:deleted', { appId });
    return true;
  }

  private deleteRecursive(path: string) {
    const stat = vfs.stat(path);
    if (stat?.type === 'directory') {
      const items = vfs.listDir(path, SYSTEM_VFS_APP_ID) || [];
      for (const item of items) {
        this.deleteRecursive(`${path}/${item}`);
      }
    }
    vfs.delete(path, SYSTEM_VFS_APP_ID);
  }

  /**
   * Get the entry HTML for a generated app, with CSS and JS inlined
   * so it works in an iframe without path resolution issues.
   */
  getInlinedEntry(appId: string): string | null {
    const appDir = `${APPS_DIR}/${appId}`;
    let html = vfs.readFile(`${appDir}/index.html`, SYSTEM_VFS_APP_ID);
    if (!html) return null;
    const css = vfs.readFile(`${appDir}/styles.css`, SYSTEM_VFS_APP_ID) || '';
    const js = vfs.readFile(`${appDir}/app.js`, SYSTEM_VFS_APP_ID) || '';

    // Inline CSS
    html = html.replace(
      /<link[^>]*href=["']styles\.css["'][^>]*>/gi,
      `<style>\n${css}\n</style>`
    );
    // Inline JS
    html = html.replace(
      /<script[^>]*src=["']app\.js["'][^>]*><\/script>/gi,
      `<script>\n${js}\n</script>`
    );
    // If no link/script tags found, append
    if (css && !html.includes('<style>')) {
      html = html.replace('</head>', `<style>\n${css}\n</style>\n</head>`);
    }
    if (js && !html.includes('<script>')) {
      html = html.replace('</body>', `<script>\n${js}\n</script>\n</body>`);
    }
    return html;
  }
}

export const appGenerator = new AppGenerator();
